# Generated by Django 5.2.5 on 2026-03-17 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animaldet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip_address',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ip_address',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
