# Generated by Django 5.2.5 on 2025-09-02 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=100)),
                ('count', models.IntegerField()),
                ('behaviour', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('camera_id', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Timestamp of the animal sighting')),
            ],
        ),
    ]
