# Generated by Django 5.2.5 on 2025-09-07 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animaldb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('camera_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('addtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='animal',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
